### ISSUE TITLE
Error occurs when try to build from source: No module named build

### ISSUE THREAD

**Issue by LZhen0711** [wukan1986/polars_ta#5]
vscode ➜ /workspaces/demo/polars_ta (main) $ python -m build
/opt/conda/bin/python: No module named build

vscode ➜ /workspaces/demo/polars_ta (main) $ ls -la
total 44
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 .
drwxrwxrwx 1 root   root    512 Aug 10 05:20 ..
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 .git
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 .github
-rw-r--r-- 1 vscode vscode 3078 Aug 10 05:20 .gitignore
-rw-r--r-- 1 vscode vscode 1062 Aug 10 05:20 LICENSE
-rw-r--r-- 1 vscode vscode 8897 Aug 10 05:20 README.md
-rw-r--r-- 1 vscode vscode 3828 Aug 10 05:20 compare.md
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 examples
-rw-r--r-- 1 vscode vscode 3120 Aug 10 05:20 nan_to_null.md
-rw-r--r-- 1 vscode vscode 4192 Aug 10 05:20 point_in_time.md
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 polars_ta
-rw-r--r-- 1 vscode vscode  956 Aug 10 05:20 pyproject.toml
-rw-r--r-- 1 vscode vscode   52 Aug 10 05:20 requirements.txt
-rw-r--r-- 1 vscode vscode   38 Aug 10 05:20 setup.py
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 tests
-rw-r--r-- 1 vscode vscode 2427 Aug 10 05:20 thinking_about_TA.md
drwxr-xr-x 1 vscode vscode  512 Aug 10 05:20 tools

**Comment by wukan1986** [comment]
pip install build

**Comment by LZhen0711** [comment]
Thanks a lot
